title: ARTJ 199 Final Project
email: drshika2@illinois.edu
author: Drshika Asher

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9" 

# disqus:
#   shortname: example-com
#
# rrss:
  # discord: hoola
  # facebook: hola
  # twitter: Hola
  # instagram: Hola
  # linkedin: Hola
  # pinterest: hola
  # whatsapp: 123
  # telegram: 123
  # email: email
